---

- name: create temp directories
  ansible.builtin.file:
    path: {{ dotfiles_clone_path }}
    state: directory

- name: create temp directories
  ansible.builtin.file:
    path: {{ packages_clone_path }}
    state: directory

- name: Clone packages repository
  ansible.builtin.git:
    repo: https://github.com/natsukashiixo/packages
    dest: "{{ packages_clone_path }}"
    version: main
    update: true

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/natsukashiixo/dotfiles_pub
    dest: "{{ dotfiles_clone_path }}"
    version: main
    update: true

- name: create temp directories
  ansible.builtin.file:
    path: {{ dotfiles_clone_path }}
    state: absent
    tags:
      - cleanup

- name: create temp directories
  ansible.builtin.file:
    path: {{ packages_clone_path }}
    state: absent
    tags:
      - cleanup