---
- name: First run provision Maika
  hosts: maika
  become: true

  pre_tasks:
    - include_role:
        name: yay
    - include_role:
        name: repos
    - include_role:
        name: common
    - include_role:
        name: preflight

  roles:
    - configure_make
    - packages
    - samba
    - sddm
    - services
    - cron

  post_tasks:
    - include_role:
        name: cleanup
