---
- name: Install pacman preflight packages
  community.general.pacman:
    name:
      - arch-install-scripts
      - dkms
      - base-devel
      - git
      - steam
      - pacman-contrib
      - retroarch
      - starship
      - rofi
      - thunar
      - ncdu
      - plocate
      - ark
      - ghostty
      - zsh
      - hyprpaper
      - imagemagick
      - kernel-modules-hook
      - lsd
      - mpv
      - nano
      - nvtop
      - btop
      - thunar-archive-plugin
      - nerd-fonts
      - uv
      - wev
      - wl-clipboard
      - firefox
      - docker
      - docker-compose
      - fastfetch
      - flatpak
      - cifs-utils
      - xorg-xrandr
      - libinput
      - libinput-tools
      - dunst
      - swayosd
      - socat
      - mangohud
      - lib32-mangohud
      - goverlay
      - python-requests
      - waybar
    state: present

- name: Install yay packages
  ansible.builtin.command: "yay -S --noconfirm --needed {{ item }}"
  loop:
    - atlauncher-bin
    - brave-bin
    - chromium-widevine
    - heroic-games-launcher-bin
    - protonhax
    - protonplus
    - proton-ge-custom-bin
    - xpadneo-dkms
    - yay
    - bzmenu
    - iwmenu
    - antimicrox-git
    - helium-browser-bin
  changed_when: false
  become: true
  become_user: "{{ target_user }}"

- name: Install webapps
  ansible.builtin.command: "{{ dotfiles_clone_path }}/{{ inventory_hostname }}/scripts/create_webapp_automated.py {{ item }}"
  loop:
    - "--app-name=Youtube --app-url=https://www.youtube.com/tv"
    - "--app-name=YoutubeMusic --app-url=https://music.youtube.com"
    - "--app-name=Twitch --app-url=https://www.twitch.tv"
  become: true
  become_user: "{{ target_user }}"

- name: Copy scripts to /usr/local/bin
  ansible.builtin.copy:
    remote_src: true
    src: "{{ dotfiles_clone_path }}/{{ inventory_hostname }}/scripts/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
    owner: root
    group: root
  loop:
    - antimicrox-hyprdaemon
    - install-webapp
    - toggle_waybar
  become: true
