---
- name: Install pacman preflight packages
  community.general.pacman:
    name:
      - arch-install-scripts
      - dkms
      - base-devel
      - git
      - steam
      - pacman-contrib
      - retroarch
      - starship
      - rofi
      - thunar
      - ncdu
      - plocate
      - ark
      - antimicrox
      - ghostty
      - zsh
      - hyprpaper
      - imagemagick
      - kernel-modules-hook
      - lsd
      - mpv
      - nano
      - nvidia-utils
      - python3
      - nvtop
      - btop
      - thunar-archive-plugin
      - nerd-fonts
      - uv
      - wev
      - wl-clipboard
      - firefox
      - docker
      - docker-compose
      - fastfetch
      - flatpak
      - cifs-utils
      - xorg-xrandr
      - libinput
      - libinput-tools
      - dunst
      - swayosd
      - socat
      - mangohud
      - lib32-mangohud
      - goverlay
  state: present

# path here kinda feels wrong?
- name: Install yay
  include_tasks: ../yay/tasks/install.yml

- name: Install yay packages
  ansible.builtin.command: "yay -S --noconfirm {{ item }}"
  loop:
    - atlauncher-bin
    - brave-bin
    - chromium-widevine
    - heroic-games-launcher-bin
    - protonhax
    - protonplus
    - proton-ge-custom-bin
    - xpadneo-dkms
    - yay
    - bzmenu
    - iwmenu
    - sunshine-git
  changed_when: false

- name: install webapps
  ansible.builtin.command: "/home/{{ target_user }}/scripts/create_webapp_automated.py {{ item }}"
  loop:
    - "--app-name=Youtube --app-url=https://www.youtube.com/tv"
    - "--app-name=YoutubeMusic --app-url=https://music.youtube.com"
    - "--app-name=Twitch --app-url=https://www.twitch.tv"
  become: true
  become_user: "{{ target_user }}"
